"""empty message

Revision ID: af5351deb7b7
Revises: fc8e8796f1c8
Create Date: 2021-02-02 05:26:45.739576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5351deb7b7'
down_revision = 'fc8e8796f1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_name_key', 'files', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('files_name_key', 'files', ['name'])
    # ### end Alembic commands ###
